CREATE TABLE Shipping(
orderid INTEGER,
memid VARCHAR(40) NOT NULL,
b_id VARCHAR(20) NOT NULL,
name VARCHAR(10) NOT NULL,
mail VARCHAR(40) NOT NULL,
phone VARCHAR(20) NOT NULL,
address VARCHAR(120) NOT NULL,
PRIMARY KEY(orderid),
FOREIGN KEY(orderid) REFERENCES Orders(orderid) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(memid) REFERENCES Member(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(b_id) REFERENCES Bread(b_id) ON DELETE CASCADE ON UPDATE CASCADE
)default CHARSET=utf8;

SELECT * FROM Shipping;
